# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NetworkRequestExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NetworkRequestExample
  pod 'NetworkRequestKit', :git => 'https://github.com/yoxisem544/NetworkRequestKit', :tag => '2.0.0-alpha.1'

  target 'NetworkRequestExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
