# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NetworkRequestExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NetworkRequestExample
  pod 'NetworkRequestKit', '~> 1.1.2'

  target 'NetworkRequestExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
